id=input("Enter ID:")
age=input("Enter your age")
salary=input("Enter salary")
name=input("Enter your name")
experience=input("Enter exp:")
print("Employee Details")
print(f"ID :",id)
print(f"Age:",age)
print(f"Salary:",salary)
print(f"Name:",name)
print(f"Experience:",experience)
